### 请求用户
GET http://localhost:3000/api/users


### 新建用户
POST http://localhost:3001/users HTTP/1.1
Content-Type: application/json

{
  "email" : "cdc@exdple.com",
  "password": "123456",
  "name": "ccccc"
}
### 用户注册
POST http://localhost:3000/api/users/signup HTTP/1.1
Content-Type: application/json

{
  "email" : "cdc@fdcxcs.com",
  "password": "123456",
  "name": "ccccc"
}
### 用户登录
POST http://localhost:3001/users/signin HTTP/1.1
Content-Type: application/json

{
  "email" : "cdc@exddsaple.com",
  "password": "123456",
  "name": "ccccc"
}
### 用户登出
POST http://localhost:3001/users/signout HTTP/1.1
Content-Type: application/json

{
  "email" : "cdc@exddsaple.com",
  "password": "123456",
  "name": "ccccc"
}

### 获取用户
GET http://localhost:3001/users/whoami

### 创建post
POST http://localhost:3001/posts HTTP/1.1
Content-Type: application/json

{
  "title": "",
  "pic": "https://example.com/test.jpg"
}

### 查询post
GET http://localhost:3001/posts

### like a post
POST http://localhost:3001/posts/like/1
Content-Type: application/json

{
  "userId": 1
}

### 上传文件
POST http://localhost:3001/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.jpg"
Content-Type: image/jpg

< ./1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
